//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Browser.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define ID_COMMON1                      102
#define ID_HOME                         102
#define IDP_FAILED_TO_CREATE            103
#define ID_DATAVIEW                     104
#define ID_DEFINITION                   105
#define ID_FILE_PRINTF                  106
#define ID_PREVIOUS                     107
#define ID_FULLROW_SELECT               108
#define ID_INDICATOR_MELDING            109
#define ID_INDICATOR_TIME               110
#define ID_LISTCOPY                     111
#define ID_NEXT                         112
#define ID_NEW_BROWSER                  113
#define ID_OPTIONS                      114
#define ID_POPUP_ADJUSTWIDTH            115
#define IDC_SQL_DATABASE_NAME_X         116
#define ID_REFRESH                      117
#define ID_HORIZ_EXPAND                 118
#define ID_SELECTALL                    119
#define IDR_MAINFRAME                   120
#define IDR_BROWSETYPE                  121
#define IDB_MENU1                       122
#define IDB_TREEIMAGE                   123
#define IDC_CANCEL_REQUERY              124
#define IDC_HLINK                       125
#define IDC_EXECUTE                     126
#define IDC_EYEICON                     127
#define IDC_FREE_DISK_SPACE             128
#define IDC_FREE_MEM                    129
#define IDC_IPEDIT                      130
#define IDC_JOIN                        131
#define IDC_PHYSICAL_MEM                132
#define IDC_TOTAL_DISK_SPACE            133
#define IDB_BACKGROUND                  134
#define IDR_BROWSERDOC                  135
#define IDD_SETTINGS                    136
#define IDD_LIMITS_X                    137
#define IDD_DATA_TYPES                  138
#define IDD_DRIVERINFO                  139
#define IDD_FUNCTIONS                   140
#define IDD_IDENTIFIERS                 141
#define IDD_MISC1_X                     142
#define IDD_MISC2                       143
#define IDD_SUPPORTED_SQL_X             144
#define IDB_IMAGELIST                   145
#define IDB_COLDTOOLBAR                 246
#define IDB_HOTTOOLBAR                  247
#define IDC_BROWSERTYPE                 602
#define IDS_DEFAULTFONT                 700
#define IDS_DEFAULTTEXTFONT             701
#define IDS_ERROR_BOF                   702
#define IDS_ERROR_EOF                   703
#define IDS_PROPSHT_CAPTION             704
#define IDC_CURSOR_LIB                  705
#define IDW_COMBO                       800
#define PIND                            900
#define PINU                            901
#define CG_IDR_POPUP_MAIN_FRAME         902
#define CG_IDS_DISK_SPACE               903
#define CG_IDS_DISK_SPACE_UNAVAIL       904
#define CG_IDS_PHYSICAL_MEM             905
#define ID_HYPERLINK_OPEN               906
#define IDR_CNTR_INPLACE                907
#define IDC_DSN                         1000
#define IDC_RECORDSET_SIZE              1001
#define IDC_SQL_USER_NAME               1001
#define IDC_API_FUNCTIONS               1001
#define IDC_SQL_SERVER_NAME             1002
#define IDC_SQL_FUNCTIONS               1002
#define IDC_SPLITTERLOCK                1003
#define IDC_SQL_DBMS_NAME               1003
#define IDC_AT_ADD                      1003
#define IDC_SQL_DBMS_VER                1004
#define IDC_AT_DROP                     1004
#define IDC_BGBITMAP                    1005
#define IDC_SQL_DRIVER_NAME             1005
#define IDC_SQL_EXPRESSIONS_IN_ORDERBY  1005
#define IDC_ORIONSTATIC                 1006
#define IDC_DATA_TYPE_LIST              1006
#define IDC_SQL_DRIVER_VER              1006
#define IDC_SQL_GROUP_BY                1006
#define IDC_SQL_DRIVER_ODBC_VER         1007
#define IDC_SQL_ORDER_BY_COLUMNS_IN_SELECT 1007
#define IDC_BTEXT                       1008
#define IDC_SQL_TYPE                    1008
#define IDC_SQL_OUTER_JOINS             1008
#define IDC_PRECISION                   1009
#define IDC_SQL_SQ_CORRELATED_SUBQUERIES 1009
#define IDC_BROWSERBUTTON               1010
#define IDD_PREFIX_SUFFIX               1010
#define IDC_SQL_LIKE_ESCAPE_CLAUSE      1010
#define IDD_CREATE_PARAMS               1011
#define IDC_SQL_ODBC_VER                1011
#define IDC_SQL_SQ_COMPARISON           1011
#define IDC_DEFAULT_PASSWORD            1012
#define IDC_NULLABLE                    1012
#define IDC_SQL_ODBC_API_CONFORMANCE    1012
#define IDC_SQL_SQ_EXISTS               1012
#define IDC_ODBCCURSOR                  1013
#define IDC_CASE_SENSITIVE              1013
#define IDC_SQL_ODBC_SQL_CONFORMANCE    1013
#define IDC_SQL_SQ_IN                   1013
#define IDC_ROWSETSIZE                  1014
#define IDC_SEARCHABLE                  1014
#define IDC_SQL_ODBC_SAG_CLI_CONFORMANCE 1014
#define IDC_SQL_SQ_QUANTIFIED           1014
#define IDC_DEFAULTDB                   1015
#define IDC_UNSIGNED                    1015
#define IDC_SQL_ODBC_SQL_OPT_IEF        1015
#define IDC_SQL_U_UNION                 1015
#define IDC_DEFAULTUSER                 1016
#define IDC_MONEY                       1016
#define IDC_SQL_U_UNION_ALL             1016
#define IDC_ALIASES                     1017
#define IDC_AUTO_INCREMENT              1017
#define IDC_SQL_PS_POSITIONED_DELETE    1017
#define IDC_SYSTEMTABLES                1018
#define IDC_MINIMUM_SCALE               1018
#define IDC_SQL_ACTIVE_CONNECTIONS      1018
#define IDC_SQL_PS_POSITIONED_UPDATE    1018
#define IDC_VIEWS                       1019
#define IDC_MAXIMUM_SCALE               1019
#define IDC_SQL_ACTIVE_STATEMENTS       1019
#define IDC_SQL_PS_SELECT_FOR_UPDATE    1019
#define IDC_PRINTTOPROGRAM              1020
#define IDC_CONVERSIONS                 1020
#define IDC_SQL_MULT_RESULT_SETS        1020
#define IDC_COLUMNWIDTH                 1021
#define IDC_SQL_FILE_USAGE              1021
#define IDC_SQL_TXN_CAPABLE             1021
#define IDC_SQL_DATA_SOURCE_READ_ONLY   1022
#define IDC_SQL_CURSOR_COMMIT_BEHAVIOR  1022
#define IDC_SQL_TXN_READ_UNCOMMITTED    1023
#define IDC_EDIT5                       1024
#define IDC_SQL_CURSOR_ROLLBACK_BEHAVIOR 1024
#define IDC_STRINGDELIMITER             1025
#define IDC_SQL_TXN_REPEATABLE_READ     1025
#define IDC_QUERYTIMEOUT                1026
#define IDC_SQL_TXN_READ_COMMITTED      1026
#define IDC_SQL_ACCESSIBLE_PROCEDURES   1027
#define IDC_SQL_TXN_SERIALIZABLE        1027
#define IDC_SQL_ACCESSIBLE_TABLES       1028
#define IDC_QUALIFIED_TABLE_NAMES       1028
#define IDC_SQL_DEFAULT_TXN_ISOLATION   1029
#define IDC_SQL_COLUMN_ALIAS            1029
#define IDC_SQL_MULTIPLE_ACTIVE_TXN     1030
#define IDC_SQL_CORRELATION_NAME        1030
#define IDC_SQL_NEED_LONG_DATA_LEN      1031
#define IDC_SQL_NON_NULLABLE_COLUMNS    1032
#define IDC_SQL_PROCEDURES              1033
#define IDC_SQL_CONCAT_NULL_BEHAVIOR    1034
#define IDC_SQL_OWNER_TERM              1035
#define IDC_SQL_NULL_COLLATION          1035
#define IDC_SQL_PROCEDURE_TERM          1036
#define IDC_SQL_ROW_UPDATES             1036
#define IDC_SQL_QUALIFIER_TERM          1037
#define IDC_SQL_TABLE_TERM              1038
#define IDC_SQL_MAX_BINARY_LITERAL_LEN  1042
#define IDC_SQL_MAX_CHAR_LITERAL_LEN    1043
#define IDC_SQL_MAX_COLUMN_NAME_LEN     1044
#define IDC_SQL_MAX_COLUMNS_IN_GROUP_BY 1045
#define IDC_SQL_MAX_COLUMNS_IN_INDEX    1046
#define IDC_SQL_MAX_COLUMNS_IN_ORDER_BY 1047
#define IDC_SQL_MAX_COLUMNS_IN_SELECT   1048
#define IDC_SQL_BP_UPDATE               1048
#define IDC_SQL_MAX_COLUMNS_IN_TABLE    1049
#define IDC_SQL_FD_FETCH_RELATIVE       1049
#define IDC_SQL_MAX_CURS0R_NAME_LEN     1050
#define IDC_SQL_MAX_INDEX_SIZE          1051
#define IDC_SQL_MAX_OWNER_NAME_LEN      1052
#define IDC_SQL_MAX_PROCEDURE_NAME_LEN  1053
#define IDC_SQL_MAX_QUALIFIER_NAME_LEN  1054
#define IDC_SQL_MAX_ROW_SIZE            1055
#define IDC_SQL_MAX_ROW_SIZE_INCLUDES_LONG 1056
#define IDC_SQL_MAX_STATEMENT_LEN       1057
#define IDC_SQL_MAX_TABLE_NAME_LEN      1058
#define IDC_SQL_MAX_TABLES_IN_SELECT    1059
#define IDC_SQL_MAX_USER_NAME_LEN       1060
#define IDC_SQL_TIMEDATE_ADD_INTERVALS  1063
#define IDC_SQL_TIMEDATE_DIFF_INTERVALS 1064
#define IDC_ODBC_KEYWORDS               1066
#define IDC_DRIVER_KEYWORDS             1068
#define IDC_SQL_IDENTIFIER_CASE         1069
#define IDC_SQL_SPECIAL_CHARACTERS      1070
#define IDC_SQL_IDENTIFIER_QUOTE_CHAR   1071
#define IDC_SQL_BP_CLOSE                1071
#define IDC_SQL_BP_DELETE               1072
#define IDC_SQL_BP_DROP                 1073
#define IDC_SQL_QUALIFIER_LOCATION      1074
#define IDC_SQL_BP_SCROLL               1074
#define IDC_SQL_QUALIFIER_NAME_SEPARATOR 1075
#define IDC_SQL_BP_TRANSACTION          1075
#define IDC_SQL_FD_FETCH_NEXT           1076
#define IDC_SQL_QUOTED_IDENTIFIER_CASE  1077
#define IDC_SQL_BP_OTHER_HSTMT          1077
#define IDC_SQL_SEARCH_PATTERN_ESCAPE   1078
#define IDC_SQL_FD_FETCH_FIRST          1078
#define IDC_SQL_FD_FETCH_LAST           1079
#define IDC_SQL_FD_FETCH_PRIOR          1080
#define IDC_SQL_FD_FETCH_ABSOLUTE       1081
#define IDC_SQL_FD_FETCH_BOOKMARK       1083
#define IDC_SQL_GD_ANY_COLUMN           1084
#define IDC_SQL_GD_ANY_ORDER            1085
#define IDC_SQL_GD_BLOCK                1086
#define IDC_SQL_GD_BOUND                1087
#define IDC_SQL_LCK_NO_CHANGE           1088
#define IDC_SQL_LCK_EXCLUSIVE           1089
#define IDC_SQL_LCK_UNLOCK              1090
#define IDC_SQL_OU_DML_STATEMENTS       1091
#define IDC_SQL_OU_PROCEDURE_INVOCATION 1092
#define IDC_SQL_OU_TABLE_DEFINITION     1093
#define IDC_SQL_OU_INDEX_DEFINITION     1094
#define IDC_SQL_OU_PRIVILEGE_DEFINITION 1095
#define IDC_SQL_POS_POSITION            1096
#define IDC_SQL_POS_REFRESH             1097
#define IDC_SQL_POS_UPDATE              1098
#define IDC_SQL_POS_DELETE              1099
#define IDC_SQL_POS_ADD                 1100
#define IDC_SQL_QU_DML_STATEMENTS       1101
#define IDC_SQL_QU_PROCEDURE_INVOCATION 1102
#define IDC_SQL_QU_TABLE_DEFINITION     1103
#define IDC_SQL_QU_INDEX_DEFINITION     1104
#define IDC_SQL_QU_PRIVILEGE_DEFINITION 1105
#define IDC_SQL_SCCO_READ_ONLY          1106
#define IDC_SQL_SCCO_LOCK               1107
#define IDC_SQL_SCCO_OPT_ROWVER         1108
#define IDC_SQL_SCCO_OPT_VALUES         1109
#define IDC_SQL_SO_FORWARD_ONLY         1110
#define IDC_SQL_SO_STATIC               1111
#define IDC_SQL_SO_KEYSET_DRIVEN        1112
#define IDC_SQL_SO_DYNAMIC              1113
#define IDC_SQL_SO_MIXED                1114
#define IDC_SQL_SS_ADDITIONS            1115
#define IDC_SQL_SS_DELETIONS            1116
#define IDC_SQL_SS_UPDATES              1117
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_ADJUSTWIDTH                  32769
#define ID_RECORD_REQUERY               32770
#define ID_CHK_ALWAYS_ON_TOP            32771
#define ID_ALWAYS_ON_TOP                32771
#define ID_COMBO_BOX                    32772
#define ID_ALWAYS_ON_TOP_YES            32773
#define ID_ALWAYS_ON_TOP_NO             32774
#define ID_HELP_ID                      32775
#define ID_ODBC_INFO                    32776
#define ID_FILE_COUNT                   32777
#define ID__COUNT                       32778
#define ID_Menu                         32779
#define ID_SQL_COUNT                    32780
#define ID_FILE_OPEN_ODBC               32781
#define ID_FILE_SAVE32782               32782
#define ID_FILE_OPEN32783               32783
#define ID_FILE_SAVEAS                  32784

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           200
#endif
#endif
